# TODO: i will setup a nginx web page using dockefile
FROM ubuntu:latest
WORKDIR /app
ENV MIACHAEL_CLASS=DOCKER
RUN apt update
RUN apt install -y nginx
COPY michael-demo.txt /app/michael-demo.txt
# ADD https://example.com/archive.zip /app/archive.zip  
# this will download the file from the url and add it to the container at the specified location
EXPOSE 80
ENTRYPOINT ["nginx","-g", "daemon off;"]
# CMD ["-g", "daemon off;"]
# host port - laptop port or ec2 instance port
# container port - tied to container # ask the developer